repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      #  args: ['--maxkb=2048']
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
     # - id: go-imports
      - id: no-go-testing
      - id: golangci-lint
      - id: go-unit-tests
  - repo: local
    hooks:
      - id: go-test-coverage
        name: Go Test Coverage
        description: Checks for go tests coverage
        entry: bash -c 'echo >/dev/tty; go test ./... -cover &>/dev/tty; echo >/dev/tty;'
        language: system
        always_run: true
        pass_filenames: false
      - id: osv-scanner
        name: osv-scanner
        description: Vulnerability scanner written in Go which uses the data provided by https://osv.dev
        entry: bash -c 'echo >/dev/tty;$GOPATH/bin/osv-scanner scan ./* &>/dev/tty; echo >/dev/tty;'
        always_run: true
        pass_filenames: false
        language: golang
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.38.0
    hooks:
      - id: eslint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
